language: ruby

sudo: false

rvm:
  - 2.0
  - 2.1

env:
  - RAILS=master AREL=master DB=sqlite
  - RAILS=master AREL=master DB=mysql
  - RAILS=master AREL=master DB=postgres

before_script:
  - mysql -e 'create database ransack collate utf8_general_ci;'
  - mysql -e 'use ransack;show variables like "%character%";show variables like "%collation%";'
  - psql -c 'create database ransack;' -U postgres
